### ISSUE TITLE
Sanitize input for plots

### ISSUE THREAD

**Issue by dwysocki** [astroswego/plotypus#16]
Our plots use `LaTeX` for formatting. As a side-effect, this means that if a filename contains a `LaTeX` syntax error, it will crash the program. Here's a [link](https://stackoverflow.com/questions/2627135/how-do-i-sanitize-latex-input) on sanitizing input for `LaTeX`.

**Comment by earlbellinger** [comment]
https://github.com/astroswego/plotypus/commit/9fbd0c6a52b763076cdf8b18d26a756b44afa3a1

Sanitized!

**Comment by earlbellinger** [comment]
I should mention that I didn't sanitize "\" because one shouldn't get that far anyway due to directories. Maybe I'm wrong though (Windows does exist, after all.)

**Comment by dwysocki** [comment]
Solution: Don't support Windows.
