### ISSUE TITLE
Test if arctangent correction in phase coefficient is necessary

### ISSUE THREAD

**Issue by dwysocki** [astroswego/plotypus#34]
Currently, `Fourier.phase_shifted_coefficients` adds `0`, `pi`, or `2*pi` to the `Phi_k` coefficients, depending on which quadrant `(a_k, b_k)` lies in.
```python
Phi_k       = numpy.arctan(a_k/b_k)
Phi_k[Q23] += numpy.pi
Phi_k[Q4]  += 2.0*numpy.pi
```
I am going to test that this correction is actually necessary. To do this, I am going to write a test script, and add a flag to `Fourier.phase_shifted_coefficients`, `correction`. The test script will make lightcurves with both `correction=True` and `False`, use `numpy.assert_almost_equal` to check if they're actually equal, and also compare the `R^2` between the two computed lightcurves, and the actual data points.

**Comment by earlbellinger** [comment]
Is this solved now?

**Comment by dwysocki** [comment]
It is solved. The correction I was applying is actually the `arctan2` function ([wikipedia](https://en.wikipedia.org/wiki/Atan2)). Since we have been doing a cosine series, the correct formulation is `Phi_k = numpy.arctan2(-a_k, b_k)`. For sine series I believe it is `Phi_k = numpy.arctan2(b_k, a_k)`. We can add the option to output sine at some point. So that settles it.

**Comment by dwysocki** [comment]
That "some point" is actually now. e39184e496cdd01155ff5f5818febceb65cf4529
