### ISSUE TITLE
Multiple period discovery

### ISSUE THREAD

**Issue by earlbellinger** [astroswego/plotypus#4]
The get lightcurve method should not only accept as argument multiple periods, but also detect multiple periods in lieu of them being supplied. After discovering the main period, find the residuals and repeat the process. (Perhaps this can be done recursively.) The period, light curve, and phased data should be returned for each period.

**Comment by earlbellinger** [comment]
redundant

**Comment by dwysocki** [comment]
This has been absorbed by #58
