### ISSUE TITLE
Add option for turning off shifting to max light 

### ISSUE THREAD

**Issue by earlbellinger** [astroswego/plotypus#48]

**Comment by earlbellinger** [comment]
I think this is superseded

**Comment by dwysocki** [comment]
For now I went ahead and added this feature anyway. We'll remove it soon enough.
fe542b4c987849deb0f1c5b5c48ce17029bda9f0

**Comment by earlbellinger** [comment]
In the other case we can turn it off by specifying a shift of 0


Earl Bellinger

**Comment by dwysocki** [comment]
I've removed the feature, and replaced it with a number. `--shift=0` to turn it off, `--shift=N` to set it to a specific shift, and by default it will shift to max light.
