### ISSUE TITLE
Supply desired shift (with max light as default)

### ISSUE THREAD

**Issue by earlbellinger** [astroswego/plotypus#53]
When computing color (V-I), it is necessary to apply the same shift to V as was applied to I. The reason for this is because there exists a real physical phase shift between the two bands, so shifting both to their respective max lights destroys meaningful information. 

At present we phase all light curves with epoch t_0 = 0 and then shift to max light. This is the correct procedure for I band, but for V band we need to be able to supply the shift that brought I band to max light. The solution I propose is to allow the user to pass either (1) a desired shift value, or (2) a file with columns Name Shift. The default behavior should be to shift to max light.

**Comment by dwysocki** [comment]
We already have a "periods" file with columns

| Name | Period0 | Period1 | ... |

Why not make a unified "parameters" file (or a better name) containing a header row with column names (like "Name", "Period", and "Shift")? So you could call plotypus with a `--parameters file.dat`, and it would pull all the needed information out. If we keep adding on more options for individual parameters, the complexity level of calling plotypus is going to keep increasing.

We would probably need to add pandas as a dependency to make this easy to implement, as its `DataFrame` abstraction is meant for precisely this sort of task.

**Comment by earlbellinger** [comment]
I both like and dislike this idea. I like it because we're going to be
pulling the desired shifts from the output of a run of plotypus already
anyway, so we can pull the periods from that same file. We just need to
select the Name Period Shift columns (using that nifty unix command --
what's it called?).

However, it's a somewhat complex solution. What if I specify two periods
and a shift? Three periods? How do we resolve these cases? (Maybe
DataFrame is the solution.)


Earl Bellinger

**Comment by dwysocki** [comment]
For now, I've gone ahead and added a `--shift` option that takes a single number to shift all light curves by, and defaults to max light. bbcbcfd4286bf5a9c30014831b03770f54ae3a01

**Comment by dwysocki** [comment]
If we do the file containing periods and shifts, we can do a selection on a pandas `DataFrame` using a common prefix. So we might want to add an argument group `Metadata` or `Parameters` or what have you, that not only has an option for a filename, but also options for the column prefixes. So maybe it would default to using `Period` and `Shift`, but another user might want `P` and `S` because they have a file already formatted like that.

An example call might look like
```bash
$ plotypus ... --parameters param_table.dat --period-prefix P --shift-prefix S
```

**Comment by dwysocki** [comment]
As a temporary feature, we are going to add support for a file containing only star names and their shifts. See #55

**Comment by dwysocki** [comment]
The unified `parameters` file has been adopted f65e14eceb78cbaca53d1a1e4d89c3a9823b44f7

For now it only allows a single period, but that will change soon.
