### ISSUE TITLE
Truncate long numbers

### ISSUE THREAD

**Issue by earlbellinger** [astroswego/plotypus#69]
The output of plotypus has really long numbers. We should truncate them. This will also make the output more readable.

**Comment by dwysocki** [comment]
Doesn't the `-f/--fmt` flag allow us to set the formatting? Maybe we should just change the # of digits in the default?

**Comment by earlbellinger** [comment]
oic.

yes.

let's do that.

**Comment by dwysocki** [comment]
So the issue, it seems, is not the default # of digits, but the fact that some fields aren't being formatted with it, specifically `Period`, `R^2`, and `MSE`. The real solution is to apply the formatting to those, which I'll do now.

**Comment by dwysocki** [comment]
This has been fixed as of #80
