### ISSUE TITLE
Rename plotypus.py to cli.py

### ISSUE THREAD

**Issue by dwysocki** [astroswego/plotypus#71]
I think the naming should be honest to what it is: `plotypus.py` really only deals with the CLI, so we should rename it to `cli.py`. Objections?

**Comment by earlbellinger** [comment]
seems fine

**Comment by dwysocki** [comment]
I'll do this after the other changes are made, since this doesn't really affect anything, except being annoying if something else is in-progress.

**Comment by dwysocki** [comment]
I changed my mind. This has been done in #81
